[shell]
program = "pwsh"

[window]
dimensions = { columns = 110, lines = 29 }
padding = { x = 16, y = 16 }
dynamic_padding = true

[font]
normal = { family = "RecursiaMDSNF" }
bold = { family = "RecursiaMDSNF" }
italic = { family = "RecursiaMDSNF" }
bold_italic = { family = "RecursiaMDSNF" }
size = 10.5

[cursor]
style = {shape = "Block", blinking = "Always"}

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "V", mods = "Alt|Shift", action = "ToggleViMode" }
]

[colors.primary]
foreground = "#B6C4F2"
background = "#1C1E26"

[colors.normal]
black =   "#B6C4F2"
red =     "#E06C75"
green =   "#D19A66"
yellow =  "#64D1A9"
blue =    "#FFD88C"
magenta = "#56B6C2"
cyan =    "#C678DD"
white =   "#B6C4F2"

[colors.bright]
black =   "#B6C4F2"
red =     "#E06C75"
green =   "#D19A66"
yellow =  "#64D1A9"
blue =    "#FFD88C"
magenta = "#56B6C2"
cyan =    "#C678DD"
white =   "#B6C4F2"

[colors.dim]
black =   "#B6C4F2"
red =     "#E06C75"
green =   "#D19A66"
yellow =  "#64D1A9"
blue =    "#FFD88C"
magenta = "#56B6C2"
cyan =    "#C678DD"
white =   "#B6C4F2"
